name: yesod-scaffold
synopsis: Yesod scaffolding tools
description: See README
maintainer: Michael Snoyman <michael@snoyman.com>
license: MIT
github: yesodweb/yesod-scaffold
category: Development

ghc-options: -Wall -Werror

dependencies:
- base
- rio
- rio-orphans
- project-template
- conduit
- optparse-simple

executables:
  yesod-scaffold:
    main: Main.hs
    source-dirs: app
    other-modules:
    - Paths_yesod_scaffold
